apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: boardgame
  name: boardgame-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: boardgame
  type: NodePort
